#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements_dev.txt
python3 -m pip install --requirement requirements_test.txt

sudo apt-get update
# For Python 3.11
sudo apt-get install -y ffmpeg libpcap0.8
# For Python 3.12
#sudo apt-get install -y ffmpeg libturbojpeg0-dev libpcap0.8