name: Pre-release tests

on:
  workflow_dispatch:

jobs:
  tests:
    name: Run pre-release tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        include:
          - python-version: "3.10"
            requirements: "requirements_test310.txt"
            pytest_all_ha_versions: "pytest_all_ha_versions_python310"
          - python-version: "3.11"
            requirements: "requirements_test311.txt"
            pytest_all_ha_versions: "pytest_all_ha_versions_python311"
          - python-version: "3.12"
            requirements: "requirements_test312.txt"
            pytest_all_ha_versions: "pytest_all_ha_versions_python312"
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4"
      - name: Setup Python
        uses: "actions/setup-python@v5"
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: python3 -m pip install -r ${{ matrix.requirements }}
      - name: Run test script
        run: bash ${{ github.workspace }}/scripts/${{ matrix.pytest_all_ha_versions }}